version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/databases/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dockerpw
      - POSTGRES_USER=docker
      - POSTGRES_DB=test